server:
  mode: anarchy-1

mysql:
  host: localhost
  user: root
  password: "сайнес гпт кодер"
  database: reports

redis:
  host: localhost
  port: 6379
  user: ""
  password: "сайнес гпт кодер"
  channel: reports